### ISSUE TITLE
stonesense: sigsegv on exit

### ISSUE THREAD

**Issue by ewtoombs** [DFHack/stonesense#35]
When stonesense is running and DF is closed, I get a segmentation fault with the following backtrace:
```gdb
#0  0xf70ae546 in pthread_mutex_lock () from /usr/lib32/libpthread.so.0
#1  0xf71b96d2 in pthread_mutex_lock () from /usr/lib32/libc.so.6
#2  0xf6d487ed in ?? () from /usr/lib32/libX11.so.6
#3  0xf6d6321d in XrmDestroyDatabase () from /usr/lib32/libX11.so.6
#4  0xf6d4a4d3 in _XFreeDisplayStructure () from /usr/lib32/libX11.so.6
#5  0xf6d38249 in XCloseDisplay () from /usr/lib32/libX11.so.6
#6  0xf78e46e9 in ?? () from /usr/lib32/libSDL-1.2.so.0
#7  0xf78ed2c3 in ?? () from /usr/lib32/libSDL-1.2.so.0
#8  0xf78dbea9 in SDL_VideoQuit () from /usr/lib32/libSDL-1.2.so.0
#9  0xf78b36dd in SDL_QuitSubSystem () from /usr/lib32/libSDL-1.2.so.0
#10 0xf78b3789 in SDL_Quit () from /usr/lib32/libSDL-1.2.so.0
#11 0xf7deeb5f in SDL_Quit () from ./hack/libdfhack.so
#12 0xf749473d in main (argc=1, argv=0xffffd914)
    at /build/dwarffortress/src/dwarf_fortress_unfuck/g_src/enabler.cpp:797
#13 0xf70db64e in __libc_start_main () from /usr/lib32/libc.so.6
#14 0x0804c9a1 in ?? ()
```
I've been trying to recover a core file, but `ulimit -c 1` doesn't seem to have any effect. I am running libx11 1.6.2 and sdl 1.2.15.

This only happens when I run stonesense, so I am tentatively calling this a bug in stonesense. Anyway, see if you can reproduce it. All I had to do was

1. Run dfhack.
2. Run stonesense from the dfhack console while DF was still in the menu.
3. Close DF by hitting 'Quit' in the menu.

**Comment by ewtoombs** [comment]
PS: I generated a core file, but it's 300 megs, which is obviously far too big to post here. If you really need it, I'll find a way.
